### ISSUE TITLE
Plugin is incompatible with the latest Intellij IDEA 2022.2.1

### ISSUE THREAD

**Issue by denbkh** [Pushpavel/AutoCp#101]
Hi, I get this error when try to load the plugin from the zip archive:
![image](https://user-images.githubusercontent.com/4642384/187209433-01ae10a0-d0ac-45e3-b3be-13863d339dba.png)
Tested on Intellij IDEA 2022.2.1 (Build #IU-222.3739.54, built on August 16, 2022)

**Comment by Pushpavel** [comment]
Updated in the latest release: [v0.7.5](https://github.com/Pushpavel/AutoCp/releases/tag/v0.7.5)
