### ISSUE TITLE
Default setup unfavorable for java

### ISSUE THREAD

**Issue by brubrz** [Pushpavel/AutoCp#104]
It is not a bug, but an inconvenience when using java.

The default naming scheme creates a the following folder structure:
my-cp-project
-- Codeforces - Codeforces Round ABC
---- B. Foo Bar
------ Main.java
-- Codeforces - Codeforces Round XYZ
---- A. Baz Qik
------ Main.java

Autocp sets the folders as excluded in the project structure. This disables syntax highlighting in the ide. Auto-complete works though. When I add any of the folders as a content root, then syntax highlighting works, but as soon as I have more than one Main,java file. I get a naming conflict, because there can't be two Main.java classes on the classpath. When I rename Main.java or any of the folders it resides in, then this breaks autocp, even if I specify, the new path in the run configuration.

I would really love to have more than one solution in my project, without running into this issue.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - IDE Intellij Ultimate 
 -  Programming Language java

Workaround is to have one contest per project.

**Comment by Pushpavel** [comment]
Thanks for filing this issue, It is indeed a bug, Autocp excludes the solution file in the root module and creates a dedicated module for each solution file (the .iml file in the solution directory),I think the name of this .iml was causing these issues (everything after first dot is being removed like A.iml is all that's left for the module name leading to conflicts with other contests).
