### ISSUE TITLE
Plugin is incompatible with the latest CLion Version CLion 2022.3

### ISSUE THREAD

**Issue by LadnerJonas** [Pushpavel/AutoCp#108]
![image](https://user-images.githubusercontent.com/92096842/205058910-489f1615-5499-4f4e-bef3-dd52d95831b2.png)

**Comment by Pushpavel** [comment]
Fixed in 84392c27ddae318f4077dc6e28c7244b87a51f8d, check [v0.7.8](https://github.com/Pushpavel/AutoCp/releases/tag/v0.7.8)

**Comment by LadnerJonas** [comment]
Thank you! 🚀
