### ISSUE TITLE
Test Framework quit unexpectedly

### ISSUE THREAD

**Issue by LoLZeS666** [Pushpavel/AutoCp#15]
I can't run my code due to this error:
![image](https://user-images.githubusercontent.com/72292088/125192001-047ef180-e263-11eb-9e9e-ef6ce7fdca02.png)

also please put up a detailed guide on how to use it since i cant create a configuration for the generated file in cmakelists

**Comment by Pushpavel** [comment]
Are you able to run g++ from a regular terminal? I think this could be the issue. 
If you are using ```clang``` change build command for c++ in <kbd>Settings / Preferences</kbd> > <kbd>AutoCp</kbd> basically change g++ to clang++

>  i cant create a configuration for the generated file in cmakelists

I don't know what u mean by that. to create a configuration try 
- Right-click generated file > Run 'Your File' or 
- Right-click generated file > More Run/Debug > Run 'Your File'

I will try to change this to more appropriate like Run 'Your File' with AutoCp or something like that in the next update

> also please put up a detailed guide on how to use it

I will try my best to write articles as soon as I got some important features ready for this plugin

**Comment by LoLZeS666** [comment]
Hi, thanks for the quick reply.
I fixed the problem of the testing framework quitting, it was due to my newer mingw installation which i forgot to add to PATH.
However, now the plugin just gives me wrong answer on an accepted solution. Is this a known bug or am i missing something?

Also, by creating a run configuration i meant that adding the file to cmakelists.txt using the add single file for execution plugin doesn't work since it always contains a whitespace, so if I want to run the code locally do i need to create another file and use it?

Thanks

**Comment by Pushpavel** [comment]
> However, now the plugin just gives me a wrong answer on an accepted solution. Is this a known bug or am i missing something?
Yes, It is a bug fixed it just now, will release it soon along with other changes.

> Also, by creating a run configuration i meant that adding the file to cmakelists.txt using the add single file for execution plugin doesn't work since it always contains a whitespace, so if I want to run the code locally do i need to create another file and use it?

remove or change whitespaces to something else for now.  u won't need additional files for running the code.

**Comment by LoLZeS666** [comment]
Ah thanks!
Great plugin just needs some polishing :)
