### ISSUE TITLE
Limit on File template size

### ISSUE THREAD

**Issue by abhishek593** [Pushpavel/autoCP#49]
**Describe the bug**
Is there a limit on the number of characters for the File template? I have a live template that I have been using, but when I use the same template, it creates the folder but doesn't create any files. When I remove some of the lines from my template, it can create the files as well. 

**To Reproduce**
https://ideone.com/u8PL9b
This is the template that I have pasted on Ideone.

**Expected behavior**
Large file templates should also be allowed.

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10]
 - IDE [e.g. CLion]
-  Programming Language [e.g. C++]

**Comment by Pushpavel** [comment]
```#pragma``` was not the issue. Only ```#define``` is the culprit. ```#define``` being wrongly used did not raise any parsing error which would have been notified. instead, it raised a generic null pointer exception stopping the file generation. I will try to come up with a useful error message for it. btw, If you want to get rid of these kinds of issues better wrap the entire template within ```#[[template]]#```
