### ISSUE TITLE
Don't treat c++ "cerr(stderr)" as a RUNTIME ERROR

### ISSUE THREAD

**Issue by mym0404** [Pushpavel/AutoCp#54]
Very thank you for this plugin. It is very useful.

**Is your feature request related to a problem? Please describe.**
I am using `cerr` as local debugging with local macro. 

Not only me, other competitive programmers may use `cerr` with debugging.

Even the test case corrects with `cout(stdout)`, when I print with `cerr(stderr)` the judge will be failed like the following.

![image](https://user-images.githubusercontent.com/33388801/139916773-e31145f4-3d34-45c8-8d6f-c4eca7088bf7.png)

I don't know it is related with internal system or behavior of c++. I am not good at c++ well. If it is, then close issue 😅

**Describe the solution you'd like**
Don't treat stdout as a RUNTIME ERROR

**Comment by Pushpavel** [comment]
Hi mym0404, I had no idea that online judges ignore ```stderr``` if ```stdout``` is right. The current implementation of the local judge ignores ```stdout``` if there is anything in ```stderr```. Thanks for bringing it up, love to solve it.

**Comment by mym0404** [comment]
Yes many online judges treats `stderr` as a error. So programmers remove debugging line before their submission.
But using `stderr` as useful for debugging in local environment.
For example, this is my template.
```cpp
#ifdef LOCAL
template<size_t S>
string to_string(const bitset<S> &x) { return x.to_string(); }
string to_string(const string &x) { return '"' + x + '"'; }
string to_string(char x) { return string{'\'', x, '\''}; }
string to_string(bool x) { return x ? "true" : "false"; }
template<class H, class T>
string to_string(const pair<H, T> &x) { return "(" + to_string(x.fi) + ", " + to_string(x.se) + ")"; }
template<class T>
string to_string(T x) {
   string ret = "[";
   for (const auto &i: x) ret += to_string(i) + ", ";
   if (sz(ret) > 1) ret = ret.substr(0, sz(ret) - 2);
   return ret += "]";
}
string to_string(const char *x) { return {x}; }
string to_string() { return ""; }
template<class H, class... T>
string to_string(H h, T... t) { return to_string(h) + ", " + to_string(t...); }
#define debug(...) sizeof( (char[]){#__VA_ARGS__} ) == 1 ? cerr << endl \
: cerr << "[" << #__VA_ARGS__ << "]: " << to_string(__VA_ARGS__) << endl
#else
#define debug(...) 1
#endif
```

If I define `LOCAL` only my local machine, then OJ compiler doesn't matter.
It prints debugging line in only my local machine like the following.
![image](https://user-images.githubusercontent.com/33388801/140096274-0e457e4c-3a90-46d6-9caf-92cbafbe9854.png)

Also I can submit this code without removing `debug(1)`. Because OJ doesn't define `LOCAL` macro.

AutoCP is local testing tool and seems to this behavior is incompatible in some case like me.

It will be wonderful if I can use `stderr` for AutoCP also.

But it is your choice. I just suggest this 😀
