### ISSUE TITLE
Import test case only but generate file

### ISSUE THREAD

**Issue by mym0404** [Pushpavel/AutoCp#55]
**Is your feature request related to a problem? Please describe.**
Now, this chrome extension works well for generating a new file in CLION editor.

But if it can import testcase only for current opened file, it maybe wonderful.

I don't want to make new file for a new problem.

**Describe the solution you'd like**
Chrome extension supports "importing testcase only for opened cpp file(remove previous test cases also)"

**Comment by Pushpavel** [comment]
You want to use the same file for every problem right?
 
The biggest issue with this approach is that It would take around 4-5 seconds for importing the test cases from the browser which you will be doing each time you change the problem for that file and you also need to take care of removing the previous problem's code in that file. Generating all the problems files at once is more simpler and advantageous.

I believe the advantage of using a single file is that you always have only the file of the current problem in the project view. (I too sometimes get confused with finding the next problem's file 😅). So this is the actual problem that needs to be addressed.

For now, to keep the working directory clean with only one file, I would suggest parsing each problem separately and removing the file each time you complete a problem. Feel free to add anything that I have missed.

**Comment by mym0404** [comment]
Thank you for response. Yes I wanted single cpp file for each problems during solving OJ not only contest.
But it is not a big issue i think. In contest your suggestion is more useful.
I close this issue.
