### ISSUE TITLE
Not compatible with the version of your running IDE (IntelliJ IDEA 2022.1, PyCharm 2022.1.1)

### ISSUE THREAD

**Issue by sunovivid** [Pushpavel/AutoCp#84]
**Is your feature request related to a problem? Please describe.**
I'm using IntelliJ IDEA 2022.1 and PyCharm 2022.1.1. When I try to install the plugin from the marketplace, there is a warning message `Not compatible with the version of your running IDE (IntelliJ IDEA 2022.1, PyCharm 2022.1.1)` and I can't install the plugin.

![image](https://user-images.githubusercontent.com/13927747/168410572-788afd49-17e4-40cd-acff-8c7db4c76400.png)

**Describe the solution you'd like**
I hope to use this awesome plugin for latest PyCharm.

**Describe alternatives you've considered**
 I also tried installing the plugin from ZIP but IDE shows `Plugin 'AutoCp' (version 'v0.7.3') is not compatible with the current version of the IDE, ~~`.

![image](https://user-images.githubusercontent.com/13927747/168410581-ce52a255-7415-4e66-901b-0794980c4b5b.png)

**Additional context**
This is my first issue for GitHub open source project so please tell me if I missed some important notice or broke community rules.

**Comment by Pushpavel** [comment]
Hi @sunovivid, this was fixed in v0.7.4 which was not properly published, thanks for reminding me. There seems to be some issues while publishing, I am debugging them and will release it soon. btw, you did it nice on your first issue. congrats

**Comment by Pushpavel** [comment]
Hi @sunovivid, [v0.7.4](https://github.com/Pushpavel/AutoCp/releases/tag/v0.7.4) is now available to download as zip.
