### ISSUE TITLE
Non-ascii letters support

### ISSUE THREAD

**Issue by sunovivid** [Pushpavel/AutoCp#86]
**Is your feature request related to a problem? Please describe.**
Non-ascii letters in the problem name disappeared so I can't use this nice plugin at Backjoon Online Judge, because most problems on this site are Korean.

For example, if a problem has non-ascii letters like `Dr. Spaceman의 특별한 알고리즘`, AutoCp generates a file which has only an alphanumeric name like `Dr_Spaceman__`.

Original problem: https://www.acmicpc.net/problem/12353
![image](https://user-images.githubusercontent.com/13927747/170524308-9c49b91c-f1ba-44f1-b9ea-13df712e050c.png)

**Describe the solution you'd like**
In my opinion, non-ascii characters in the filename should be allowed as in most OS.

In the example above, it could be `Dr_Spaceman의_특별한_알고리즘` or `Dr. Spaceman의 특별한 알고리즘`

(I think allowing non-ascii letters and allowing whitespaces or special letters are different topics)

**Describe alternatives you've considered**
I found some lines associated with refining filenames.

![image](https://user-images.githubusercontent.com/13927747/170527131-ef965dce-6c05-4deb-b4fd-1aa1531cd6ff.png)

I tried to test in IDE but I failed with some configuration issues.

So I only tested in Kotlin tests and verified it works.

![image](https://user-images.githubusercontent.com/13927747/170531426-24c72ee9-813f-45cc-89a8-04aa2e75dec2.png)

I want to make a pull request but I'm wondering how do you think about this issue.

**Comment by sunovivid** [comment]
Thank you for your reply!

I made a pull request just now.

And I'm still wondering your opinion about allowing whitespaces and special characters in the filename which is allowed in OS.

Because I want to save the problem name as it is.

Here is [what I referenced](https://stackoverflow.com/a/47455094/19194418)

**Comment by Pushpavel** [comment]
I was worried compilers won't be fine with allowing white-spaces or special chars, It was unfamiliar to see them in program files and also I saw [cph](https://github.com/agrawal-d/cph) extension in vs-code patching filenames. But, I tried running few compilers with these chars in filename and it seems to work fine. So, I think it is a good idea.

**Comment by Pushpavel** [comment]
released in [v0.7.5](https://github.com/Pushpavel/AutoCp/releases/tag/v0.7.5)
